name: Release AddOn

# triggers when pushing a tag
on:
  push:
    tags:
      - '**'

jobs:
  release: # "release" is a job, you can name it anything you want
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # reads history for commit changelog

      - uses: BigWigsMods/packager@v2
        with:
          cf-api-key: ${{ secrets.CF_API_KEY }}
          wowi-api-token: ${{ secrets.WOWI_API_TOKEN }}
          wago-api-token: ${{ secrets.WAGO_API_TOKEN }}
